<?php
/**
  (c) Matthew "Master_Odin" Peveler <matt.peveler@gmail.com>

  Licensed under the MIT License
  
  For the full copyright and license information, please view the LICENSE
  file that was distributed with this source code.

  Generates a json file filled with rankings generated by GosuGamers

  API Version: v1
*/

if ($_SERVER['SERVER_NAME'] == "127.0.0.1" || $_SERVER['SERVER_NAME'] == "localhost") {
    ini_set('display_errors',1);
    ini_set('display_startup_errors',1);
    error_reporting(-1);
}

include('vendor/simple_html_dom.php');

$html = file_get_html("http://www.gosugamers.net/starcraft2/rankings#player");
$players = array();
$a = $html->find('.simple',0);
$i = 0;
foreach($a->find('tr.ranking-link') as $player) {
  if ($i == 20)
    break;
  $rank   = trim($player->find('.ranking',0)->plaintext);
  $handle = trim($player->find('span',2)->plaintext);
  $player_id = $player->getAttribute('data-id');
  $player_info = file_get_html("http://www.gosugamers.net/starcraft2/rankings/show/player/".$player_id);
  $name   = trim($player_info->find('p.sub-header',0)->plaintext);
  $wins   = trim($player_info->find('.wins',0)->plaintext);
  $loses  = trim($player_info->find('.losses',0)->plaintext);
  $points = trim($player->find('.numbers',0)->plaintext);
  $link   = "http://www.gosugamers.net/starcraft2/".trim($player_info->find('.base',0)->find('a',0)->href);
  //print $rank." ".$name." ".$points."<br />";
  $players[$rank] = array(
      'rank'   => $rank,
      'handle' => $handle,
      'name'   => $name,
      'wins'   => $wins,
      'loses'  => $loses,
      'points' => $points,
      'link'   => $link
  );
  $i++;
}

$save = array('gosugamers_rankings' => $players);
$json = json_encode($save);
$fp = fopen('GosuGamersRankings/v1/api.json','w');
fwrite($fp,$json);
fclose($fp);

echo $json;
?>